set_output:
  name: Set PID output
  description: Set or reset the PID controller output.
  target:
    entity:
      integration: simple_pid_controller
      domain: sensor
  fields:
    preset:
      name: Preset
      description: Use a preset output: zero_start, last_known_value or startup_value.
      selector:
        select:
          options:
            - zero_start
            - last_known_value
            - startup_value
    value:
      name: Value
      description: Manual output value between output_min and output_max.
      selector:
        number:
          step: 0.1
