name: Hassfest

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  
jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
