name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
      - edited
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: peaceiris/actions-issue-labeler@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}